name: Push images to ghcr.io

on:
  push:

permissions: write-all

jobs:
  push:
    name: "Build Docker"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [discord]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA for tag
        id: truncatedString
        run: echo "string=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/year/${{ matrix.service }}:latest
            ghcr.io/${{ github.repository_owner }}/year/${{ matrix.service }}:${{ steps.truncatedString.outputs.string }}
